### ISSUE TITLE
Publishing unable to publish repository directly

### ISSUE THREAD

**Issue by oddomatik** [ALLOcloud/OpenAPT#5]
in aptly we publish a repo directly. The specs suggest this should be possible, but unless I'm missing something - it doesn't seem to be working when applied in practice.

```
{
  "repositories": {
    "example-jammy": {
      "distribution": "jammy"
    }
  }
  "publishings": {
      "example-jammy": {
        "repository": "example-jammy",
        "distribution": "example-jammy"
    }
  }
}
```

results in:

```
# openapt --dry-run --debug --limit publishing:example-jammy aptly.json
/usr/local/lib/python3.8/dist-packages/allocloud/openapt/__init__.py:37: YAMLLoadWarning: calling yaml.load() without Loader=... is deprecated, as the default Loader is unsafe. Please read https://msg.pyyaml.org/load for full details.
  _schema = yaml.load(f)
Traceback (most recent call last):
  File "/usr/local/bin/openapt", line 8, in <module>
    sys.exit(main())
  File "/usr/local/lib/python3.8/dist-packages/allocloud/openapt/__main__.py", line 64, in main
    run(**args)
  File "/usr/local/lib/python3.8/dist-packages/allocloud/openapt/__init__.py", line 51, in run
    entities.load(_schema, context)
  File "/usr/local/lib/python3.8/dist-packages/allocloud/openapt/models.py", line 389, in load
    self.append(Publishing(name=name, context=context, **params))
TypeError: __init__() got an unexpected keyword argument 'repository'
```

**Comment by oddomatik** [comment]
It should be noted - specifying a snapshot for the repo and publishing that does work, but this doesn't meet our needs as it takes hours to publish a snapshot change for a single package, and publishing repos directly IS something supported by aptly.

**Comment by hlobit** [comment]
Hi @oddomatik,
that was not implemented because it seemed to us this was just a shortcut from aptly CLI.
Even aptly documentation [warns against](https://www.aptly.info/doc/aptly/publish/repo/) usage of `aptly publish repo` command:

> It is not advised to publish local repositories directly unless repository is used to host testing versions of packages that change frequently. For production usage please [create snapshot](https://www.aptly.info/doc/aptly/snapshot/create/) from repository and [publish it](https://www.aptly.info/doc/aptly/publish/snapshot/).

However, if I understand correctly: it might allow keeping a big, frequently changed repo published without much overhead. If it's your use case, it's one thing that could be added, your MR is welcome :+1:

An additional thought: isn't the publication of a local repo the matter of a "oneshot" command in aptly ? The main purpose of OpenAPT was to organize publishings in a descriptive layout using snapshots and operations on snapshots to ease publication. If you need one aplty repo published as it is, I don't really see the added value of OpenAPT here except mapping exactly what you have in aptly - this was not our intent.

Regards, looking forward to seeing your answer :slightly_smiling_face:

**Comment by oddomatik** [comment]
Thank you, I am basically implementing OpenAPT with ansible to attempt to automate the setup of aptly servers as much as possible. Seeing as I'm trying to shoehorn it into a role it wasn't really made for, I will rely on oneshot commands issued elsewhere to complete the setup of our repos. It is very helpful for managing upstream mirrors, so we will continue using it there.

Thank you for you work.
